gn:
  search:
    # Full text on all fields
    # 'queryBase': '${any}',
    # Full text but more boost on title match
    queryBase: 'any:(${any}) resourceTitleObject.default:(${any})^2'
    scoreConfig: >
      {
        "boost": "5",
        "functions": [
          { // Boost down member of a series
            "filter": { "exists": { "field": "parentUuid" } },
            "weight": 0.3
          },
          { // Boost down obsolete records
            "filter": { "match": { "cl_status.key": "obsolete" } },
            "weight": 0.3
          },
          {
            "gauss": {
              "dateStamp": {
                "scale": "365d",
                "offset": "90d",
                "decay": 0.5
              }
            }
          }
        ],
        "score_mode": "multiply"
      }
    sortables:
      - "relevance"
      - "createDate:desc"
      - "resourceTitleObject.default.keyword"
      - "rating:desc"
      - "popularity:desc"
    formats:
      -
        name: json
        mimeType: application/json
        responseProcessor: org.fao.geonet.common.search.processor.impl.JsonUserAndSelectionAwareResponseProcessorImpl
      -
        name: xml
        mimeType: application/xml
        responseProcessor: org.fao.geonet.common.search.processor.impl.XmlResponseProcessorImpl
      -
        name: html
        mimeType: text/html
        responseProcessor: org.fao.geonet.common.search.processor.impl.JsonUserAndSelectionAwareResponseProcessorImpl
      -
        name : dcat
        mimeType : application/dcat2+xml
        responseProcessor: org.fao.geonet.common.search.processor.impl.XsltResponseProcessorImpl
      -
        name : gn
        mimeType : application/gn+xml
        responseProcessor: org.fao.geonet.common.search.processor.impl.XsltResponseProcessorImpl
      -
        name : jsonld
        mimeType : application/ld+json
        responseProcessor: org.fao.geonet.common.search.processor.impl.JsonUserAndSelectionAwareResponseProcessorImpl
      -
        name : iso19139
        mimeType : application/iso19139+xml
        responseProcessor: org.fao.geonet.common.search.processor.impl.XsltResponseProcessorImpl
      -
        name : iso19115-3
        mimeType : application/iso19115-3+xml
        responseProcessor: org.fao.geonet.common.search.processor.impl.XsltResponseProcessorImpl
      -
        name : rss
        mimeType : application/rss+xml
        responseProcessor: org.fao.geonet.common.search.processor.impl.RssResponseProcessorImpl
    defaultMimeType: application/json
    sources:
      - "resourceTitleObject"
      - "resourceAbstractObject"
      - "resourceType"
      - "overview"
      - "uuid"
      - "schema"
      - "link"
      - "allKeywords"
      - "contactForResource"
      - "cl_status"
      - "edit"